#!/usr/bin/env bash

result=0
while read -r line; do
    first=$(echo "${line:0: -1}" | fold -w1 | sort -nr | head -n1)
    rest=${line#*$first}
    second=$(echo "$rest" | fold -w1 | sort -nr | head -n1)
    jolts="$first$second"
    ((result += jolts))
done < "$1"

echo "$result"
