#!/usr/bin/env bash

result=0
while read line; do
    jolts=""
    rest="$line"
    for (( i = -11; i <= 0; i++ )); do
        check="$rest"
        if (( i != 0 )); then
            check="${rest:0:$i}"
        fi
        biggest=$(echo "$check" | fold -w1 | sort -nr | head -n1)
        rest="${rest#*$biggest}"
        jolts="$jolts$biggest"
    done
    ((result += jolts))
done < "$1"

echo "$result"
