#!/usr/bin/env bash

lines=()

height=0
while read -r line; do
    if (( height == 0 )); then
        start="${line%S*}"
        start_x="${#start}"
    else
        if [[ $line != *^* ]]; then
            continue
        fi
        lines+=("$line")
    fi
    ((height++))
done < "$1"

beams=("$start_x")
splits=0
for (( i = 0; i < height - 1; i++ )); do
    line="${lines[i]}"
    new_beams=()
    for beam in "${beams[@]}"; do
        if [[ "${line:"$beam":1}" != '^' ]]; then
            if (( beam == last_beam )); then
                continue
            fi
            last_beam="$beam"
            new_beams+=("$beam")
            continue
        fi

        ((splits++))

        if (( last_beam != beam - 1 )); then
            new_beams+=("$((beam - 1))")
        fi

        new_beams+=("$((beam + 1))")
        last_beam="$((beam + 1))"
    done

    beams=("${new_beams[@]}")
done

echo "$splits"
