#!/usr/bin/env bash

lines=()

height=0
while read -r line; do
    if (( height == 0 )); then
        start="${line%S*}"
        start_x="${#start}"
    else
        if [[ $line != *^* ]]; then
            continue
        fi
        lines+=("$line")
    fi
    ((height++))
done < "$1"

beams=("$start_x")
duplicates=()
duplicates[start_x]=1
for (( i = 0; i < height - 1; i++ )); do
    line="${lines[i]}"
    new_beams=()
    new_duplicates=()
    for beam in "${beams[@]}"; do
        duplicate="${duplicates[beam]}"
        if [[ "${line:"$beam":1}" != '^' ]]; then
            ((new_duplicates[beam] += duplicate))
            if (( beam == last_beam )); then
                continue
            fi
            last_beam="$beam"
            new_beams+=("$beam")
            continue
        fi

        if (( last_beam != beam - 1 )); then
            new_beams+=("$((beam - 1))")
        fi
        ((new_duplicates[beam - 1] += duplicate))

        new_beams+=("$((beam + 1))")
        ((new_duplicates[beam + 1] += duplicate))
        last_beam="$((beam + 1))"
    done

    beams=("${new_beams[@]}")
    duplicates=()
    for id in "${!new_duplicates[@]}"; do
        duplicates[id]="${new_duplicates[id]}"
    done
done

sum=0
for duplicate in "${duplicates[@]}"; do
    ((sum += duplicate))
done
echo "$sum"
