#!/usr/bin/env bash

points=()
while read -r point; do
  points+=("$point")
done < "$1"

point_count="${#points[@]}"

max=0
for (( i = 0; i < point_count; i++ )); do
  IFS=, read -r x1 y1 <<< "${points[i]}"
  for (( j = i + 1; j < point_count; j++ )); do
    IFS=, read -r x2 y2 <<< "${points[j]}"
    width="$((x2 - x1))"
    width="${width#-}"
    height="$((y2 - y1))"
    height="${height#-}"
    area="$(((width + 1) * (height + 1)))"

    if (( area > max )); then
      max="$area"
    fi
  done
done
echo "$max"
