#!/usr/bin/env bash

in_ranges=true
ranges=()
fresh_count=0
while read -r line; do
    if [[ -z "$line" ]]; then
        in_ranges=false
        continue
    fi

    if $in_ranges; then
        ranges+=("$line")
    else
        for range in "${ranges[@]}"; do
            IFS=- read start end <<< "$range"
            if (( line >= start && line <= end )); then
                ((fresh_count++))
                break
            fi
        done
    fi
done < "$1"

echo "$fresh_count"
