#!/usr/bin/env bash

declare -A room
height=0
while read -r line; do
    width="${#line}"
    for (( x = 0; x < width; x++ )); do
        room[$x,$height]="${line:$x:1}"
    done
    ((height++))
done < "$1"

count-neighbours() {
    local x="$1"
    local y="$2"

    local neighbours=0
    for (( dy = -1; dy <= 1; dy++ )); do
        local check_y=$((y + dy))
        if (( check_y < 0 || check_y >= height )); then
            continue
        fi

        for (( dx = -1; dx <= 1; dx++ )); do
            local check_x=$((x + dx))
            if (( check_x < 0 || check_x >= width )); then
                continue
            fi

            if (( dx == 0 && dy == 0 )); then
                continue
            fi

            if [[ "${room[$check_x,$check_y]}" == '@' ]]; then
                ((neighbours++))
            fi
        done
    done

    echo "$neighbours"
}

accessible=0
for (( y = 0; y < height; y++ )); do
    for (( x = 0; x < width; x++ )); do
        if [[ "${room[$x,$y]}" != '@' ]]; then
            continue
        fi

        neighbours="$(count-neighbours "$x" "$y")"

        if (( neighbours < 4 )); then
            ((accessible++))
        fi
    done
done

echo "$accessible"
