#!/usr/bin/env bash

declare -A room
height=0
while read -r line; do
    width="${#line}"
    for (( x = 0; x < width; x++ )); do
        room["$x","$height"]="${line:"$x":1}"
    done
    ((height++))
done < "$1"

count-neighbours() {
    local x="$1"
    local y="$2"

    local neighbours=0
    for (( dy = -1; dy <= 1; dy++ )); do
        local check_y=$((y + dy))
        if (( check_y < 0 || check_y >= height )); then
            continue
        fi

        for (( dx = -1; dx <= 1; dx++ )); do
            local check_x=$((x + dx))
            if (( check_x < 0 || check_x >= width )); then
                continue
            fi

            if (( dx == 0 && dy == 0 )); then
                continue
            fi

            if [[ "${room["$check_x","$check_y"]}" == '@' ]]; then
                ((neighbours++))
            fi
        done
    done

    echo "$neighbours"
}

declare -A neighbour_counts
for (( y = 0; y < height; y++ )); do
    for (( x = 0; x < width; x++ )); do
        if [[ "${room["$x","$y"]}" != '@' ]]; then
            neighbour_counts["$x","$y"]=-1
            continue
        fi

        neighbours="$(count-neighbours "$x" "$y")"
        neighbour_counts["$x","$y"]="$neighbours"
    done
done

total_removed=0
while true; do
    removed=0

    for (( y = 0; y < height; y++ )); do
        for (( x = 0; x < width; x++ )); do
            if (( neighbour_counts["$x","$y"] == -1 )); then
                continue
            fi

            if (( neighbour_counts["$x","$y"] >= 4 )); then
                continue
            fi

            neighbour_counts["$x","$y"]=-1
            ((removed++))
            for (( dy = -1; dy <= 1; dy++ )); do
                check_y=$((y + dy))
                if (( check_y < 0 || check_y >= height )); then
                    continue
                fi

                for (( dx = -1; dx <= 1; dx++ )); do
                    check_x=$((x + dx))
                    if (( check_x < 0 || check_x >= width )); then
                        continue
                    fi

                    if (( dx == 0 && dy == 0 )); then
                        continue
                    fi

                    if (( neighbour_counts["$check_x","$check_y"] == -1 )); then
                        continue
                    fi

                    ((neighbour_counts["$check_x","$check_y"]--))
                done
            done
        done
    done

    if (( removed == 0 )); then
        break
    fi

    ((total_removed += removed))
done
echo "$total_removed"
