#!/usr/bin/env bash

declare -A network
declare -A indegrees

while read -r line; do
    IFS=':' read -r from to <<< "$line"
    to="${to:1}"
    network["$from"]="$to"
    IFS=" " read -ra branches <<< "$to"
    for branch in "${branches[@]}"; do
        ((indegrees["$branch"]++))
    done
done < "$1"

topological=()
queue=("svr")
while (( "${#queue}" > 0 )); do
    top="${queue[0]}"
    queue=("${queue[@]:1}")
    topological+=("$top")

    IFS=" " read -ra branches <<< "${network["$top"]}"
    for branch in "${branches[@]}"; do
        ((indegrees["$branch"]--))
        if (( indegrees["${branch}"] == 0 )); then
            queue+=("$branch")
        fi
    done
done

for (( i = 0; i < "${#topological[@]}"; i++ )); do
    node="${topological[i]}"
    if [[ "$node" == "fft" ]]; then
        fft_index="$i"
    fi
    if [[ "$node" == "dac" ]]; then
        dac_index="$i"
    fi
done

node_count="${#topological[@]}"
if (( fft_index < dac_index )); then
    targets=(0 "$fft_index" "$dac_index" "$((node_count - 1))")
else
    targets=(0 "$dac_index" "$fft_index" "$((node_count - 1))")
fi

total=1
for (( section = 0; section < 3; section++ )); do
    start="${targets[section]}"
    end="${targets[section + 1]}"

    unset paths
    declare -A paths
    start_node="${topological[start]}"
    end_node="${topological[end]}"
    paths["$start_node"]=1
    for (( i = start; i < end; i++ )); do
        node="${topological[i]}"
        IFS=" " read -ra branches <<< "${network["$node"]}"
        for branch in "${branches[@]}"; do
            ((paths["$branch"] += paths["$node"]))
        done
    done
    ((total *= paths["$end_node"]))
done
echo "$total"
