#!/usr/bin/env bash

declare -A test
y=0
while read -r line; do
    read -ra numbers <<< "$line"
    x=0
    for number in "${numbers[@]}"; do
        test[$x,$y]="$number"
        ((x++))
    done
    ((y++))
done < "$1"
width="$x"
height="$y"

sum=0
for (( x = 0; x < width; x++ )); do
    op=${test[$x,$((height-1))]}
    result=0
    if [[ $op == '*' ]]; then
        result=1
    fi

    for (( y = 0; y < height - 1; y++ )); do
        number=${test[$x,$y]}
        if [[ $op == '+' ]]; then
            ((result += number))
        else
            ((result *= number))
        fi
    done

    ((sum += result))
done

echo "$sum"
