#!/usr/bin/env bash

button_to_number() {
    button="$1"
    result=0
    IFS=, read -ra changes <<< "$button"
    for change in "${changes[@]}"; do
        ((result |= 2 ** change))
    done <<< "$button"
    echo "$result"
}

sum=0
while read -r line; do
    IFS=' ' read -ra parts <<< "$line"
    buttons=()
    for part in "${parts[@]}"; do
        if [[ "$part" =~ \[([.#]+)\] ]]; then
            lights="${BASH_REMATCH[1]}"
        elif [[ "$part" == \(*\) ]]; then
            length="${#part}"
            inside="${part:1:$((length - 2))}"
            change=$(button_to_number "$inside")
            buttons+=("$change")
        fi
    done

    current=0
    expected=0
    for (( i = "$(("${#lights}" - 1))"; i >= 0; i-- )); do
        ((expected <<= 1))
        if [[ "${lights:$i:1}" == '#' ]]; then
            ((expected |= 1))
        fi
    done

    queue_state=("$current")
    queue_presses=(0)
    queue_pressed=(0)
    while (( "${#queue_pressed[@]}" > 0 )); do
        top_state="${queue_state[0]}"
        top_presses="${queue_presses[0]}"
        top_pressed="${queue_pressed[0]}"
        queue_state=("${queue_state[@]:1}")
        queue_presses=("${queue_presses[@]:1}")
        queue_pressed=("${queue_pressed[@]:1}")

        if (( top_state == expected )); then
            ((sum += top_presses))
            break
        fi

        for (( i = 0; i < "${#buttons[@]}"; i++ )); do
            button="${buttons[i]}"
            if (( top_pressed & 1 << i )); then
                continue
            fi

            new_state=$((top_state ^ button))
            queue_state+=("$new_state")
            queue_presses+=("$((top_presses + 1))")
            queue_pressed+=("$((top_pressed | (1 << i)))")
        done
    done
done < "$1"

echo "$sum"
